### ISSUE TITLE
[Feature] Vertical alignment of the text

### ISSUE THREAD

**Issue by Mnaukal** [danilowoz/coverify#11]
I would like to be able to set the vertical alignment of the main text, i. e. move it up or down.
![Coverify](https://user-images.githubusercontent.com/9487592/81043907-8632fc80-8eb3-11ea-84b4-183689808e7d.jpg)
**Workaround:** I was suprised that setting the margin from browser's developer tools works and updates the generated image 😃.

**Comment by danilowoz** [comment]
Hey @Mnaukal 
To align vertically I've added some extras line breaks at top or bottom, see:

<img width="450" alt="Screenshot 2020-05-05 at 09 39 13" src="https://user-images.githubusercontent.com/4838076/81048509-6223eb00-8eb4-11ea-8f46-fe3c6fe6fe5f.png">
<img width="442" alt="Screenshot 2020-05-05 at 09 39 22" src="https://user-images.githubusercontent.com/4838076/81048523-66500880-8eb4-11ea-9f29-89abdc665b6f.png">
<img width="441" alt="Screenshot 2020-05-05 at 09 39 46" src="https://user-images.githubusercontent.com/4838076/81048525-67813580-8eb4-11ea-9032-4de63a8319d2.png">


Let me know if it works for you

**Comment by Mnaukal** [comment]
Yeah, that works. I didn't think of that, thanks.
