### ISSUE TITLE
[Bug] Unable to login

### ISSUE THREAD

**Issue by ploguus** [danilowoz/coverify#2]
I can't log in to Spotify. I entered my login info, and in the upper-right of the page, if I hover over the grey bars, it says, "Loading...." forever and ever. Tried in Firefox, Chrome, and Edge, same thing in all.

**Comment by danilowoz** [comment]
Hey, thank for letting me know. 

1. Which OS are you using? 
2. Do you have any kind of adblocker?
3. Would you mind to send me screenshot of your console/network? (make sure to do not share sensitive information)

Thanks

**Comment by ploguus** [comment]
1. Windows 10
2. Yes on Firefox, but I deactivated it and still had this problem. No adblockers on Chrome or Edge.
3. I don't know what this means. Do you mean screenshot my browser windows, when I'm trying to login? I'm not a dev, so I'm not savvy.

**Comment by ploguus** [comment]
![coverify-console](https://user-images.githubusercontent.com/22798496/80394824-a50c1000-886f-11ea-97b8-438aefc3fa87.jpg)
I hope this is what you need.

**Comment by danilowoz** [comment]
Hey @ploguus 
Could you check it right? I hope I fixed it

Thanks

**Comment by ploguus** [comment]
A different error after entering my Spotify info: "Something went wrong, please try again."

**Comment by danilowoz** [comment]
I've tested here and I didn't get any problem.
Would you mind reach me on email or twitter? Maybe we could have a call, then I can see what is happening on your computer.

danilowoz@gmail.com
https://twitter.com/danilowoz

**Comment by bunchopunch** [comment]
Hi, I'm also unable to login in Windows 10 on Chrome and Firefox, with adblock and enhanced protection turned off. I was able to authenticate the app initially, but subsequent requests cause the auth window to appear for a split second then the app returns `Something went wrong, please try again`. The Spotify network call is a 200 and includes my user data. There's no error in the console, as I assume it's being caught.

That said, Redux tools shows a `general` `USER_ERROR`. For what it's worth, it looks like the `USER_SIGN_SUCCESS` fires and contains a "`token`", `USER_LOADING` fires again, then the user and the token is removed.

![image](https://user-images.githubusercontent.com/8526819/81006360-a065cf80-8e0c-11ea-8aae-531da272cad5.png)

**Comment by danilowoz** [comment]
@bunchopunch Thanks for the details, it helped a lot!
Could you try again and let me know if it works? It doesn't happen in my computer

**Comment by Nisgrak** [comment]
I have the same error! I am premium, don't know if it's relevant

**Comment by danilowoz** [comment]
Hey, anyone available to test the latest version (v1.0.12)?
I hope I've fixed it.

**Comment by Nisgrak** [comment]
@danilowoz Same error in 1.0.12.

**Comment by bunchopunch** [comment]
I'm also continuing to see the same issue. I attempted removing the app authorization from Spotify and starting over and still saw it again.

![image](https://user-images.githubusercontent.com/8526819/82836162-590ab600-9e83-11ea-92f4-73ef40b9a4cd.png)

**Comment by danilowoz** [comment]
Hey, anyone here available to test the latest version?
I hope I've fixed it 🙏

**Comment by Nisgrak** [comment]
@danilowoz sadly didn't work 😢

**Comment by bunchopunch** [comment]
If you end up figuring this out, I'd be really curious regarding the cause.

Tried it on Firefox 79.0

- Removed from linked app Spotify 
- Disabled Cache
- Login with Spotify
- Agree
- Coverify shows: "Something went wrong please try again"

In Redux Tools:

USER_SIGN_SUCCESS
```
{
    user: {
        data: {},
        token: "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234565789"
    }
}
```

USER_ERROR:
```
  user: {
    errorMessage: 'general',
    loading: false
  }
```

![image](https://user-images.githubusercontent.com/8526819/89796009-56b11300-dae6-11ea-83dc-98a3c1895aca.png)

**Comment by danilowoz** [comment]
@bunchopunch here I go again, could you please try again the latest version? 
It just released the v1.1.2.

Thanks for helping

**Comment by danilowoz** [comment]
Hope it has fixed.

**Comment by Nisgrak** [comment]
@danilowoz It keeps happening

**Comment by bunchopunch** [comment]
Sorry for the delay getting back to this. Looks like I'm still seeing the error in redux tools with the user token being removed from the state at that point. And the "something went wrong" appears.

This was in Firefox with uBlock and enhanced tracking protection disabled for the site. And, the app does show as allowed inside the Spotify account.

![image](https://user-images.githubusercontent.com/8526819/91441562-b0774400-e82d-11ea-8dcd-7c96ce24f825.png)

Additionally, I'm now seeing (or noticing) this in the following in the console:
`Event delivery failed OnAuthorizeAccepteddue to error [object Object]`

I tried running through the process in Chrome on the off chance the object would serialize, but when complete didn't see the same console warning. Going through the process step by step I realized that the warning was actually appearing on Spotify's account authorization page. 

```
Navigated to https://accounts.spotify.com/authorize?client_id=f5be6eeb8ac84d4e954f831f4349cf92&redirect_uri=https://coverify.now.sh/&scope=ugc-image-upload%20playlist-modify-public%20playlist-modify-private%20playlist-read-private&response_type=token&show_dialog=true

0.f4bea60c4c65350cf3ed.js:1 Event delivery failed OnAuthorizeViewShowndue to error [object Object]

0.f4bea60c4c65350cf3ed.js:1 POST https://accounts.spotify.com/oauth2/analytics/event net::ERR_BLOCKED_BY_CLIENT

(This happened again when clicking the allow button on the spotify page)

0.f4bea60c4c65350cf3ed.js:1 Event delivery failed OnAuthorizeAccepteddue to error [object Object]

0.f4bea60c4c65350cf3ed.js:1 POST https://accounts.spotify.com/oauth2/analytics/event net::ERR_BLOCKED_BY_CLIENT

Navigated to https://coverify.now.sh/
```

Seeing blocked by client, I added accounts.spotify.com to my uBlock whitelist and stopped seeing all `OnAuthorizeViewShowndue` errors. But, Coverify still showed the same User Error in Redux tools.

I went through the whole thing again one more time with uBlock totally disabled for good measure and ended up still seeing the issue:

![image](https://user-images.githubusercontent.com/8526819/91444077-7445e280-e831-11ea-9aa1-0f34ecb765ea.png)

**Comment by danilowoz** [comment]
As long as Coverify has an entirely new version, I guess it has been solved.
