### ISSUE TITLE
Can't connect spotify account

### ISSUE THREAD

**Issue by pokeriscute** [danilowoz/coverify#21]
New to coverify. Cool concept but sadly I can't connect my spotify account...

1. I press the "log in with spotify" button (both the one at the top corner and the one in "my playlists" section)
2. It recognizes my account and prompts me to agree to connect spotify and coverify
3. I agree
4. It takes me back to coverify's home page and an error message saying "Something went wrong, please try again" appears

**Screenshots**
![image](https://user-images.githubusercontent.com/69802821/90402167-b8095100-e0a7-11ea-9e0f-5b9a55fa4328.png)
![image](https://user-images.githubusercontent.com/69802821/90402196-c5264000-e0a7-11ea-9f84-19d390638532.png)

**Desktop:**
 - OS: Win10
 - Browser: Chrome AND Edge
 - Version: Chrome - Chrome 84, Edge 84

**Comment by danilowoz** [comment]
Hey @pokeriscute, thanks for sharing the details about the bug. This bug has been annoying for a while and so far I'm not sure why it's happening. Anyway, I just release a new version where I tried to fix it, could you please check it again?

Please make sure you have the latest version (1.1.2):
<img width="200" alt="Screenshot 2020-08-17 at 21 01 53" src="https://user-images.githubusercontent.com/4838076/90439118-e64d5780-e0cc-11ea-9c1e-21f4bcdb7338.png">

**Comment by danilowoz** [comment]
Hope it has fixed.
