### ISSUE TITLE
Error Login

### ISSUE THREAD

**Issue by Nisgrak** [danilowoz/coverify#31]
### Description:
I try to login, the popup shows but an black page always stays.

#### Details:

In the console shows an error for a XHR, it returns 502
```
An error occurred with this application.

NO_RESPONSE_FROM_FUNCTION
```
![image](https://user-images.githubusercontent.com/19597708/107352700-742e5c00-6acc-11eb-955f-05707b055b09.png)

**Comment by danilowoz** [comment]
Hey, thanks for reporting.
Could you try again? I think it has solved

**Comment by Nisgrak** [comment]
@danilowoz Exactly same error, I make Ctrl+F5 to be sure

**Comment by danilowoz** [comment]
Would you mind trying again? @Nisgrak 
I believe I found the error

**Comment by Nisgrak** [comment]
@danilowoz same error :(
![image](https://user-images.githubusercontent.com/19597708/107617993-1c6d2d80-6c51-11eb-9d0f-45d8d1c7e15d.png)

**Comment by Nisgrak** [comment]
Now works! @danilowoz
