### ISSUE TITLE
UX Improvements

### ISSUE THREAD

**Issue by danilowoz** [danilowoz/coverify#32]
- [x] Draft label is not a button
- [x] Mobile: the style tab is completely messed up
- [x] Mobile: block background scroll when the menu is opened
- [x] Mobile: Make header is compact enough to show all information, maybe try to short the name
- [x] Mobile: Tweak on welcome, maybe remove it 
- [x] Mobile: click on the logo to go back
- [x] Mobile: Can't close the big menu
- [x] Mobile: when starts the big menu comes opened
- [x] Figure out a way to explain what is the purpose of new visitors
- [x] Update button doesn't appear on a small desktop screen
- [x] UX: Say to user is not able to do anything without login
- [x] When the user is not login, there no title at the playlist part
- [x] Desktop: close welcome after a while

**Comment by 888-222** [comment]
I used your service a time ago and liked it a lot. Looking at it today, I have to say that it feels a lot more cluttered. 
But what mostly confuses me now is what font to use. Last time it automatically selected one that looks similar
to the one Spotify uses, this is how I expect it to be. Other than that, great service! Thanks for your work

**Comment by danilowoz** [comment]
@888-222 Thanks for your feedback, just solved the issue about the font-family you mentioned.

Could you tell me what you liked most about the old version? Or what exactly is bothering you in this new version? 
The playlist selections, or the style/background part. I'd love to hear from you about what could be better in the Coverify.
