### ISSUE TITLE
Download button for cover is gone in V2.0

### ISSUE THREAD

**Issue by MustachedMario** [danilowoz/coverify#34]
Hi,

There is no download button for covers anymore since V2.0.
Well, this is seriously a dump desicion. People can't be so stupid,
to login with their spotify account, giving a untrusted cover creation
service access to their accounts.

Moving to another service...

**Comment by 4rr0wx** [comment]
I have the same problem. Even if I would like to sign in I can't because the sign in window just stays black.
I can't use anything.

Please add the download button again!

**Comment by danilowoz** [comment]
Thanks for kind words @MustachedMario.

@4rr0wx thanks for the feedback, I had planned to the download button again, it only wasn't a priority. Anyway, it seems a very used feature so, I just added in the last version.

**Comment by 4rr0wx** [comment]
Thank you for the quick fix!
I love the new functions in V2. All my playlists have covers from your website.
