### ISSUE TITLE
Wrong font size when window width is changed

### ISSUE THREAD

**Issue by Mnaukal** [danilowoz/coverify#37]
### Description:
The text is too big when the width of the browser window is smaller (than the size the cover was created in). 

I created this cover image in a maximized browser window (2560px wide). When I made the window smaller (1000px wide) and clicked on another playlist and back on this one to force it to reload, the text is too big and does not fit into the cover image.

#### Details:

Maximized browser window (2560px wide) -- Correct
![maximized](https://user-images.githubusercontent.com/9487592/113176195-81560480-924c-11eb-81f8-8b5671fdaa8c.png)

Smaller browser window (1000px wide) -- Text too big
![smaller](https://user-images.githubusercontent.com/9487592/113176132-71d6bb80-924c-11eb-99e4-d4122c16f153.png)

Browser: Firefox 87.0

**Comment by danilowoz** [comment]
:tada: This fix is included in version 2.5.2; however, you will need to resave your artboard since it doesn't have backward compatibility. 

The release is available on [GitHub release](https://github.com/danilowoz/coverify/releases/tag/v2.5.2)
