### ISSUE TITLE
[Bug] Email text is white on the mailing list

### ISSUE THREAD

**Issue by SeanCassiere** [danilowoz/coverify#52]
### Description:
The text colour of the email field for the mailing list component is white.

Since both the text and the email field background are white, the user is unable to view and verify the email address which have been typed in.

#### Details:
![Screen Cap with Devtools open](https://i.ibb.co/KjCZDdt/Screenshot-2021-08-16-at-13-30-49.png)

**Comment by SeanCassiere** [comment]
Looking at the modules folder, it seems the email field component is being styled with a hardcoded `#fff` colour.

Dir - `src/modules/Newsletter/Newsletter.tsx`

```
Lines 76-86

const Input = styled('input', {
  color: '#fff', // <---- Here the hardcoded value
  border: 0,
  padding: '1.1em 1.6em',
  borderRadius: '30px',
  marginRight: '1em',

  '@aboveSmall': {
    width: '30em',
  },
})
```

**Comment by danilowoz** [comment]
ohhh that's right! What a silly mistake! 
Would you be able to fix and open a PR? Otherwise, I can try to fix it later.

**Comment by SeanCassiere** [comment]
Sure thing!

Any specific colour you want it changed to?

**Comment by danilowoz** [comment]
https://github.com/danilowoz/coverify/blob/master/src/common/UI/Layout/theme.ts#L6 This should look good!
