### ISSUE TITLE
Exported image has a weird mask/filter

### ISSUE THREAD

**Issue by jeffjads** [danilowoz/coverify#6]
What I see on the site: 
![image](https://user-images.githubusercontent.com/12724975/80444151-8d05c080-8943-11ea-890c-e17bf3e67896.png)

What was exported:
![image](https://user-images.githubusercontent.com/12724975/80444173-9e4ecd00-8943-11ea-83d4-ca2f1af46dd7.png)

**Comment by danilowoz** [comment]
Hey @jeffjads thanks for letting me know about this bug.
It has fixed on the latest release, so could you please check it again?

Thanks

**Comment by jeffjads** [comment]
Yep, it's fixed now. Thank you!
